//! Common types, events, and commands for the gate controller

use embassy_time::Duration;

/// Door identifier
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Door {
    Left,
    Right,
}

/// Commands that can be sent to the FSM from external processes
#[derive(Debug, Clone, Copy)]
pub enum FsmCommand {
    /// Start opening sequence
    Open,
    /// Start closing sequence  
    Close,
    /// Temporarily disable autoclose (re-enabled on next open cycle)
    StopAutoClose,
}

/// Events generated by the GPI (input) process
#[derive(Debug, Clone, Copy)]
pub enum GpiEvent {
    /// Control input pulse detected (debounced)
    ControlPulse,
    /// Obstacle detected (debounced, active)
    ObstacleDetected,
    /// Obstacle cleared (debounced, inactive)
    ObstacleCleared,
}

/// Commands sent to the GPO (output) process
#[derive(Debug, Clone, Copy)]
pub enum GpoCommand {
    /// Set door open relay state
    SetDoorOpen { door: Door, active: bool },
    /// Set door close relay state
    SetDoorClose { door: Door, active: bool },
    /// Set signal lamp state
    SetLamp(LampState),
}

/// Signal lamp states
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LampState {
    /// Lamp off
    Off,
    /// Blinking at 1/2 Hz with 75% duty cycle (1.5s on, 0.5s off)
    Blinking,
}

/// FSM states for the gate controller
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GateState {
    Closed,
    Opening,
    Open,
    Closing,
}

/// Configuration for a single door
#[derive(Debug, Clone, Copy)]
pub struct DoorConfig {
    /// Delay before starting to open this door
    pub open_delay: Duration,
    /// Delay before starting to close this door
    pub close_delay: Duration,
    /// Duration of the open movement
    pub open_duration: Duration,
    /// Duration of the close movement
    pub close_duration: Duration,
}

impl DoorConfig {
    pub const fn new(
        open_delay: Duration,
        close_delay: Duration,
        open_duration: Duration,
        close_duration: Duration,
    ) -> Self {
        Self {
            open_delay,
            close_delay,
            open_duration,
            close_duration,
        }
    }
}

/// Configuration for the entire gate system
#[derive(Debug, Clone, Copy)]
pub struct GateConfig {
    pub left_door: DoorConfig,
    pub right_door: DoorConfig,
    /// If Some, doors will auto-close after this delay. If None, autoclose is disabled.
    pub autoclose_delay: Option<Duration>,
    /// How long before door movement the lamp should start blinking
    pub lamp_prestart: Duration,
}

impl Default for GateConfig {
    fn default() -> Self {
        Self {
            left_door: DoorConfig::new(
                Duration::from_millis(0),
                Duration::from_millis(0),
                Duration::from_secs(15),
                Duration::from_secs(15),
            ),
            right_door: DoorConfig::new(
                Duration::from_millis(500),
                Duration::from_millis(500),
                Duration::from_secs(15),
                Duration::from_secs(15),
            ),
            autoclose_delay: Some(Duration::from_secs(30)),
            lamp_prestart: Duration::from_secs(1),
        }
    }
}
